language: node_js
node_js:
  - "8"
#cache:
#  yarn: true
#  directories:
#    - "node_modules"
#    - "lib"
#    - "build"
script: "yarn global add parcel-bundler && yarn build"
deploy:
  provider: pages
  local-dir: build/
  skip-cleanup: true
  github-token: $GITHUB_TOKEN 
  keep-history: false
  target-branch: gh-pages
  on:
    branch: master