// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Js_dict = require("bs-platform/lib/js/js_dict.js");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var GoldenLayout = require("golden-layout");
var AceEditor$ReactTemplate = require("./bindings/AceEditor.bs.js");
var Component2$ReactTemplate = require("./Component2.bs.js");

var config = Js_dict.fromList(/* :: */[
      /* tuple */[
        "type",
        "row"
      ],
      /* :: */[
        /* tuple */[
          "content",
          /* array */[]
        ],
        /* [] */0
      ]
    ]);

var glayout = new GoldenLayout(config, "body");

glayout.init();

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, AceEditor$ReactTemplate.make("ocaml", "monokai", "test", /* array */[])), "index1");

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, Component2$ReactTemplate.make("Hello!", /* array */[])), "index2");

exports.config = config;
exports.glayout = glayout;
/* config Not a pure module */
