// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Js_dict = require("bs-platform/lib/js/js_dict.js");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var GoldenLayout = require("golden-layout");
var Ace$ReactTemplate = require("./components/ace.bs.js");
var AceEditor$ReactTemplate = require("./bindings/AceEditor.bs.js");

var React = require('react')
;

var ReactDOM = require('react-dom')
;

window.React = React
;

window.ReactDOM = ReactDOM
;

require('golden-layout/dist/goldenlayout.min.js')
;

require('golden-layout/src/css/goldenlayout-base.css')
;

require('golden-layout/src/css/goldenlayout-dark-theme.css')
;

var config = Js_dict.fromList(/* :: */[
      /* tuple */[
        "type",
        "row"
      ],
      /* :: */[
        /* tuple */[
          "content",
          /* array */[Js_dict.fromList(/* :: */[
                  /* tuple */[
                    "type",
                    "react-component"
                  ],
                  /* :: */[
                    /* tuple */[
                      "component",
                      "ace"
                    ],
                    /* [] */0
                  ]
                ])]
        ],
        /* [] */0
      ]
    ]);

var glayout = new GoldenLayout(config, "body");

glayout.registerComponent("ace", Ace$ReactTemplate.$$default);

glayout.init();

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, AceEditor$ReactTemplate.make("ocaml", "monokai", "test", /* array */[])), "index1");

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, Ace$ReactTemplate.make("bababa", /* array */[])), "index2");

exports.config = config;
exports.glayout = glayout;
/*  Not a pure module */
