// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var ReactAce = require("react-ace");
var ReasonReact = require("reason-react/src/ReasonReact.js");

((require('brace/mode/ocaml')));

((require('brace/theme/monokai')));

function make(mode, theme, name, children) {
  return ReasonReact.wrapJsForReason(ReactAce.default, {
              mode: mode,
              theme: theme,
              name: name
            }, children);
}

exports.make = make;
/*  Not a pure module */
