// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';


require('golden-layout/dist/goldenlayout.min.js')
;

require('golden-layout/dist/goldenlayout-base.js')
;

require('golden-layout/dist/goldenlayout-dark-theme.js')
;

/*  Not a pure module */
